# Generated by Django 4.2.27 on 2026-01-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('competition', 'Competition'), ('vet', 'Vet Appointment'), ('farrier', 'Farrier Visit'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='journal.rider')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='journal.horse')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
