# Generated by Django 4.2.27 on 2026-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='horse_photos/'),
        ),
    ]
