# Generated by Django 4.2.27 on 2026-01-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_horse_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('competition', 'Competition'), ('ride', 'Ride'), ('lesson', 'Lesson'), ('vet', 'Vet Appointment'), ('farrier', 'Farrier Visit'), ('other', 'Other')], max_length=20),
        ),
    ]
